# Basic
title: zknb
subtitle: Blog
description: 欢迎来到zknbの破站~
# 头像里面的标题
avatarTitle: 点击
# 头像里面的描述
avatarDesc: 进入博客主页
url: "https://blog.zknb-666.ml"

# 博客是否自动生成目录，false为不生成
enableToc: true

#Background
background: https://api.ixiaowai.cn/api/api.php

# Comment
comment:
    #livere: MTAyMC81MzcwNy8zMDE4MA==  # https://www.livere.com
    #disqus: zknb
    changyan: {appid: cywbOTzo8, conf: prod_4b0b4f9618f5c8510c3dac7597ffc448}   # http://changyan.kuaizhan.com/ 请进入 后台->安装畅言->通用代码安装 在代码处获取appid和conf
       
# Social
social:
    QQ: 2865467965
    #weibo: 5366874726 
    github: zknb-666
    # zhihu: panpanleopard
    # juejin: xxx
    #jianshu: 2ada30d8d0f7
    # twitter: 
    mail: 2865467965@qq.com

#Music
meting:
    autohide: ture
    server: tencent
    type: playlist
    id: 2139464986
    theme: ff0000

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 78dabddbcdea439ca4959d5e2057b184 

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#   id: UA-84134159-3  
#  host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 主页
   

# Navigation buttons in the front page.s
nav:
    - {title: 文章, description: 杂七杂八的东西, url: '/archive/'}   
    - {title: 标签, description: 杂七杂八的分类, url: '/tags/'}            
    - {title: 关于我, description: 一个废物, url: '/about/'}
    - {title: 下载站, description: 垃圾堆, url: 'https://pan.zknb-666.ml'}   
    


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
plugins: [jekyll-paginate]
