# Basic
title: 备考中
subtitle: 个人站
description: 欢迎来到备考中の破站~
# 头像里面的标题
avatarTitle: zknb
# 头像里面的描述
avatarDesc: 初学者
url: "https://zknb-666.gitee.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    #disqus: zknb
    #uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 5366874726 
    github: Im-joker
    # zhihu: panpanleopard
    # juejin: xxx
    #jianshu: 2ada30d8d0f7
    # twitter: 
    mail: 2865467965@qq.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 4c57ad19d45c6205e335f0f574a628cb  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
 #   id: UA-84134159-3  
  #  host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 欢迎页, description: welcone, url: '/'}
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}            
    - {title: 关于我, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


